export const SET_SEARCH_NAME = 'SET_SEARCH_NAME';
export const FETCH_SEARCH_EMPLOYEE_PENDING = 'FETCH_SEARCH_EMPLOYEE_PENDING';
export const FETCH_SEARCH_EMPLOYEE_SUCCESS = 'FETCH_SEARCH_EMPLOYEE_SUCCESS';
export const FETCH_SEARCH_EMPLOYEE_FAILED = 'FETCH_SEARCH_EMPLOYEE_FAILED';
